
const langSelector = document.getElementById('language-selector')
const farsi = document.getElementById("language-selected-fa")
const english = document.getElementById("language-selected-en")



document.documentElement.lang = langSelector.value = localStorage.getItem('langSel') || document.documentElement.lang
langSelector.onchange = () => {
   document.documentElement.lang = langSelector.value
   localStorage.setItem('langSel', langSelector.value)
}

window.addEventListener("change" , () => {
   if (document.documentElement.getAttribute('lang') == 'en') {
      document.getElementById("landing-text").innerHTML = "landing"
      document.getElementById("about-text").innerHTML = "About us";
      document.getElementById("services-text").innerHTML = "Our Services";
      document.getElementById("protofilo-text").innerHTML = "Protofilo";
      document.getElementById("team-text").innerHTML = "Our Team";
      document.getElementById("contact-text").innerHTML = "Contact Us";
      document.getElementById("landing-text-1").innerHTML = "Lorem Ipsum is a mock text produced with incomprehensible simplicity from the printing industry and using graphic designers"
      document.getElementById("landing-text-2").innerHTML = "Lorem Ipsum's fake text with the production of incomprehensible simplicity from the printing industry"
      document.getElementById("landing-text-3").innerHTML = "Lorem ipsum dolor"
      document.getElementById("landing-text-4").innerHTML = "Lorem ipsum dolor"
      document.getElementById("landing-text-5").innerHTML = "Lorem ipsum dolor"
      document.getElementById("about-header-text-1").innerHTML = "Learn more about us"
      document.getElementById("about-header-text-2").innerHTML = "Learn more about us"
      document.getElementById("about-body-text-1").innerHTML = "Lorem Ipsum is a fake text with an incomprehensible simplicity produced by the printing industry"
      document.getElementById("about-body-text-2").innerHTML = "Lorem Epsom is a fake text produced with incomprehensible simplicity from the printing industry and using graphic designers, printers and texts, but also newspapers and magazines in columns and rows as necessary."
      document.getElementById("about-body-text-3").innerHTML = "Lorem ipsum dolor"
      document.getElementById("about-body-text-4").innerHTML = "Lorem Ipsum is a mock text with an unintelligible simplicity produced by the printing industry"
      document.getElementById("about-body-text-5").innerHTML = "The list of printers and texts, but also newspapers and magazines in columns and rows as necessary"
      document.getElementById("about-body-text-6").innerHTML = "Lorem Epsom is a fake text produced with incomprehensible simplicity from the printing industry and using graphic designers, printers and texts, but also newspapers and magazines in columns and rows as necessary."
      document.getElementById("about-body-text-7").innerHTML = "Lorem ipsum dolor"
      document.getElementById("about-body-text-8").innerHTML = "Lorem Epsom is a fake text produced with printing industry and using graphic designers, printers and texts, but also newspapers and magazines."
      document.getElementById("about-body-text-9").innerHTML = "Lorem ipsum dolor"
      document.getElementById("about-body-text-10").innerHTML = "Lorem Epsom is a fake text produced with printing industry and using graphic designers, printers and texts, but also newspapers and magazines."
      document.getElementById("about-body-text-11").innerHTML = "Lorem ipsum dolor"
      document.getElementById("about-body-text-12").innerHTML = "Lorem Epsom is a fake text produced with printing industry and using graphic designers, printers and texts, but also newspapers and magazines."
      document.getElementById("about-body-text-13").innerHTML = "Lorem ipsum dolor"
      document.getElementById("about-body-text-14").innerHTML = "Lorem Epsom is a fake text produced with printing industry and using graphic designers, printers and texts, but also newspapers and magazines."
      document.getElementById("services-header-text-1").innerHTML = "services"
      document.getElementById("services-header-text-2").innerHTML = "our services"
      document.getElementById("services-body-text-1").innerHTML = "Lorem Ipsum is a fictional text"
      document.getElementById("services-body-text-2").innerHTML = "Lorem Epsom is a fake text produced with incomprehensible simplicity from the printing industry and using graphic designers, printers and texts, but also newspapers."
      document.getElementById("services-body-text-3").innerHTML = "Lorem Ipsum is a fictional text"
      document.getElementById("services-body-text-4").innerHTML = "Lorem Epsom is a fake text produced with incomprehensible simplicity from the printing industry and using graphic designers, printers and texts, but also newspapers."
      document.getElementById("services-body-text-5").innerHTML = "Lorem Ipsum is a fictional text"
      document.getElementById("services-body-text-6").innerHTML = "Lorem Epsom is a fake text produced with incomprehensible simplicity from the printing industry and using graphic designers, printers and texts, but also newspapers."
      document.getElementById("services-body-text-7").innerHTML = "Lorem Ipsum is a fictional text"
      document.getElementById("services-body-text-8").innerHTML = "Lorem Epsom is a fake text produced with incomprehensible simplicity from the printing industry and using graphic designers, printers and texts, but also newspapers."
      document.getElementById("services-body-text-9").innerHTML = "Lorem Ipsum is a fictional text"
      document.getElementById("services-body-text-10").innerHTML = "Lorem Epsom is a fake text produced with incomprehensible simplicity from the printing industry and using graphic designers, printers and texts, but also newspapers."
      document.getElementById("services-body-text-11").innerHTML = "Lorem Ipsum is a fictional text"
      document.getElementById("services-body-text-12").innerHTML = "Lorem Epsom is a fake text produced with incomprehensible simplicity from the printing industry and using graphic designers, printers and texts, but also newspapers."
      document.getElementById("portfolio-header-text-1").innerHTML = "Protofilo"
      document.getElementById("portfolio-header-text-2").innerHTML = "our Protofilo"
      document.getElementById("portfolio-body-text-1").innerHTML = "Lorem Ipsum mock text with"
      document.getElementById("portfolio-body-text-2").innerHTML = "Lorem Ipsum"
      document.getElementById("portfolio-body-text-3").innerHTML = "Lorem Ipsum mock text with"
      document.getElementById("portfolio-body-text-4").innerHTML = "Lorem Ipsum"
      document.getElementById("portfolio-body-text-5").innerHTML = "Lorem Ipsum mock text with"
      document.getElementById("portfolio-body-text-6").innerHTML = "Lorem Ipsum"
      document.getElementById("portfolio-body-text-7").innerHTML = "Lorem Ipsum mock text with"
      document.getElementById("portfolio-body-text-8").innerHTML = "Lorem Ipsum"
      document.getElementById("portfolio-body-text-9").innerHTML = "Lorem Ipsum mock text with"
      document.getElementById("portfolio-body-text-10").innerHTML = "Lorem Ipsum"
      document.getElementById("portfolio-body-text-11").innerHTML = "Lorem Ipsum mock text with"
      document.getElementById("portfolio-body-text-12").innerHTML = "Lorem Ipsum"
      document.getElementById("team-header-text-1").innerHTML = "Our professional staff"
      document.getElementById("team-header-text-2").innerHTML = "Get to know the professional staff of the Future Green Research Company"
      document.getElementById("team-body-text-1").innerHTML = "Ipsom text"
      document.getElementById("team-body-text-2").innerHTML = "Worm Epsom fake text with the production of incomprehensible simplicity from the printing industry and with stipulation"
      document.getElementById("team-body-text-3").innerHTML = "Ipsom text"
      document.getElementById("team-body-text-4").innerHTML = "Worm Epsom fake text with the production of incomprehensible simplicity from the printing industry and with stipulation"
      document.getElementById("team-body-text-5").innerHTML = "Ipsom text"
      document.getElementById("team-body-text-6").innerHTML = "Worm Epsom fake text with the production of incomprehensible simplicity from the printing industry and with stipulation"
      document.getElementById("team-body-text-7").innerHTML = "Ipsom text"
      document.getElementById("team-body-text-8").innerHTML = "Worm Epsom fake text with the production of incomprehensible simplicity from the printing industry and with stipulation"
      document.getElementById("contact-header-text-1").innerHTML = "contact us"
      document.getElementById("contact-header-text-2").innerHTML = "Contact us for more information"
      document.getElementById("contact-body-text-1").innerHTML = "contact us"
      document.getElementById("contact-body-text-2").innerHTML = "Contact us for more information"
      document.getElementById("contact-body-text-10").innerHTML = "Support... "
      document.getElementById("contact-body-text-3").innerHTML = "our address"
      document.getElementById("contact-body-text-4").innerHTML = "The address of the office of the future research company"
      document.getElementById("contact-body-text-5").innerText = "Mashhad holy shrine of  peace be upon him"
      document.getElementById("contact-body-text-6").innerHTML = "Our email"
      document.getElementById("contact-body-text-7").innerHTML = "Contact us by email"
      document.getElementById("contact-body-text-8").innerHTML = "Green research company in virtual space"
      document.getElementById("contact-body-text-9").innerHTML = "Contact us by email"
      document.documentElement.setAttribute('dir', 'ltr');
      navv.classList.add("offcanvas-start");
      navv.classList.remove("offcanvas-end");
      langSelector.style.backgroundImage="url(source/gallery/united-states-of-america-flag-large.png)"
   }
   if (document.documentElement.getAttribute('lang') == 'fa') {
      document.getElementById("landing-text").innerHTML = "صفحه نخست"
      document.getElementById("about-text").innerHTML = "درباره ما";
      document.getElementById("services-text").innerHTML = "خدمات";
      document.getElementById("protofilo-text").innerHTML = "نمونه کار ها";
      document.getElementById("team-text").innerHTML = "تیم ما";
      document.getElementById("contact-text").innerHTML = "تماس با ما";
      document.getElementById("landing-text-1").innerHTML = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است     "
      document.getElementById("landing-text-2").innerHTML = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ     "
      document.getElementById("landing-text-3").innerHTML = "لورم ایپسوم متن"
      document.getElementById("landing-text-4").innerHTML = "لورم ایپسوم متن"
      document.getElementById("landing-text-5").innerHTML = "لورم ایپسوم متن"
      document.getElementById("about-header-text-1").innerHTML = "درباره ما بیشتر بدانید"
      document.getElementById("about-header-text-2").innerHTML = "درباره ما بیشتر بدانید"
      document.getElementById("about-body-text-1").innerHTML = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم ازصنعت چاپ"
      document.getElementById("about-body-text-2").innerHTML = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است"
      document.getElementById("about-body-text-3").innerHTML = "لورم ایپسوم متن"
      document.getElementById("about-body-text-4").innerHTML = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ"
      document.getElementById("about-body-text-5").innerHTML = "لست چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است"
      document.getElementById("about-body-text-6").innerHTML = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است"
      document.getElementById("about-body-text-7").innerHTML = "لورم ایپسوم متن"
      document.getElementById("about-body-text-8").innerHTML = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است"
      document.getElementById("about-body-text-9").innerHTML = "لورم ایپسوم متن"
      document.getElementById("about-body-text-10").innerHTML = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است"
      document.getElementById("about-body-text-11").innerHTML = "لورم ایپسوم متن"
      document.getElementById("about-body-text-12").innerHTML = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است"
      document.getElementById("about-body-text-13").innerHTML = "لورم ایپسوم متن"
      document.getElementById("about-body-text-14").innerHTML = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است"
      document.getElementById("services-header-text-1").innerHTML = "خدمات"
      document.getElementById("services-header-text-2").innerHTML = "خدمات ما"
      document.getElementById("services-body-text-1").innerHTML = "لورم ایپسوم متن ساختگی"
      document.getElementById("services-body-text-2").innerHTML = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است"
      document.getElementById("services-body-text-3").innerHTML = "لورم ایپسوم متن ساختگی"
      document.getElementById("services-body-text-4").innerHTML = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است"
      document.getElementById("services-body-text-5").innerHTML = "لورم ایپسوم متن ساختگی"
      document.getElementById("services-body-text-6").innerHTML = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است"
      document.getElementById("services-body-text-7").innerHTML = "لورم ایپسوم متن ساختگی"
      document.getElementById("services-body-text-8").innerHTML = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است"
      document.getElementById("services-body-text-9").innerHTML = "لورم ایپسوم متن ساختگی"
      document.getElementById("services-body-text-10").innerHTML = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است"
      document.getElementById("services-body-text-11").innerHTML = "لورم ایپسوم متن ساختگی"
      document.getElementById("services-body-text-12").innerHTML = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است"
      document.getElementById("portfolio-header-text-1").innerHTML = "محصولات ما"
      document.getElementById("portfolio-header-text-2").innerHTML = "با نمونه محصولات شرکت پژوهش سبز آینده اشنا شوید"
      document.getElementById("portfolio-body-text-1").innerHTML = "لورم ایپسوم متن ساختگی با"
      document.getElementById("portfolio-body-text-2").innerHTML = "لورم ایپسوم متن"
      document.getElementById("portfolio-body-text-3").innerHTML = "لورم ایپسوم متن ساختگی با"
      document.getElementById("portfolio-body-text-4").innerHTML = "لورم ایپسوم متن"
      document.getElementById("portfolio-body-text-5").innerHTML = "لورم ایپسوم متن ساختگی با"
      document.getElementById("portfolio-body-text-6").innerHTML = "لورم ایپسوم متن"
      document.getElementById("portfolio-body-text-7").innerHTML = "لورم ایپسوم متن ساختگی با"
      document.getElementById("portfolio-body-text-8").innerHTML = "لورم ایپسوم متن"
      document.getElementById("portfolio-body-text-9").innerHTML = "لورم ایپسوم متن ساختگی با"
      document.getElementById("portfolio-body-text-10").innerHTML = "لورم ایپسوم متن"
      document.getElementById("portfolio-body-text-11").innerHTML = "لورم ایپسوم متن ساختگی با"
      document.getElementById("portfolio-body-text-12").innerHTML = "لورم ایپسوم متن"

      document.getElementById("team-header-text-1").innerHTML = "کادر حرفه ای ما"
      document.getElementById("team-header-text-2").innerHTML = "با کادر حرفه ای شرکت پژوهش سبز آینده اشنا شوید"
      document.getElementById("team-body-text-1").innerHTML = "ایپسوم متن"
      document.getElementById("team-body-text-2").innerHTML = "ورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفا"
      document.getElementById("team-body-text-3").innerHTML = "ایپسوم متن"
      document.getElementById("team-body-text-4").innerHTML = "ورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفا"
      document.getElementById("team-body-text-5").innerHTML = "ایپسوم متن"
      document.getElementById("team-body-text-6").innerHTML = "ورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفا"
      document.getElementById("team-body-text-7").innerHTML = "ایپسوم متن"
      document.getElementById("team-body-text-8").innerHTML = "ورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفا"
      document.getElementById("contact-header-text-1").innerHTML = "تماس با ما     "
      document.getElementById("contact-header-text-2").innerHTML = "برای اطالاعات بیشتر با ما در تماس باشید"
      document.getElementById("contact-body-text-1").innerHTML = "تماس با ما"
      document.getElementById("contact-body-text-2").innerHTML = "برای ارتباط بیشتر با ما در تماس باشید"
      document.getElementById("contact-body-text-10").innerHTML = "پشتیبانی "
      document.getElementById("contact-body-text-3").innerHTML = "آدرس ما"
      document.getElementById("contact-body-text-4").innerHTML = "آدرس دفتر شرکت پژوهش سبز آینده"
      document.getElementById("contact-body-text-5").innerText = "مشهد، حرم مطهر امام رضا (علیه السلام)."
      document.getElementById("contact-body-text-6").innerHTML = "پست الکترونیکی ما"
      document.getElementById("contact-body-text-7").innerHTML = "با ما از طریق پست الکترونیکی در ارتباط باشید"
      document.getElementById("contact-body-text-8").innerHTML = "شرکت پژوهش سبز در فضا مجازی"
      document.getElementById("contact-body-text-9").innerHTML = "با ما از طریق پست الکترونیکی در ارتباط باشید"
      document.documentElement.setAttribute('dir', 'rtl');
      navv.classList.remove("offcanvas-start");
      navv.classList.add("offcanvas-end");  
      langSelector.style.backgroundImage=" url(source/gallery/iran-flag-xs.png)"

   }
})

window.addEventListener("load" , () => {
   if (document.documentElement.getAttribute('lang') == 'en') {
      document.getElementById("landing-text").innerHTML = "landing"
      document.getElementById("about-text").innerHTML = "About us";
      document.getElementById("services-text").innerHTML = "Our Services";
      document.getElementById("protofilo-text").innerHTML = "Protofilo";
      document.getElementById("team-text").innerHTML = "Our Team";
      document.getElementById("contact-text").innerHTML = "Contact Us";
      document.getElementById("landing-text-1").innerHTML = "Lorem Ipsum is a mock text produced with incomprehensible simplicity from the printing industry and using graphic designers"
      document.getElementById("landing-text-2").innerHTML = "Lorem Ipsum's fake text with the production of incomprehensible simplicity from the printing industry"
      document.getElementById("landing-text-3").innerHTML = "Lorem ipsum dolor"
      document.getElementById("landing-text-4").innerHTML = "Lorem ipsum dolor"
      document.getElementById("landing-text-5").innerHTML = "Lorem ipsum dolor"
      document.getElementById("about-header-text-1").innerHTML = "Learn more about us"
      document.getElementById("about-header-text-2").innerHTML = "Learn more about us"
      document.getElementById("about-body-text-1").innerHTML = "Lorem Ipsum is a fake text with an incomprehensible simplicity produced by the printing industry"
      document.getElementById("about-body-text-2").innerHTML = "Lorem Epsom is a fake text produced with incomprehensible simplicity from the printing industry and using graphic designers, printers and texts, but also newspapers and magazines in columns and rows as necessary."
      document.getElementById("about-body-text-3").innerHTML = "Lorem ipsum dolor"
      document.getElementById("about-body-text-4").innerHTML = "Lorem Ipsum is a mock text with an unintelligible simplicity produced by the printing industry"
      document.getElementById("about-body-text-5").innerHTML = "The list of printers and texts, but also newspapers and magazines in columns and rows as necessary"
      document.getElementById("about-body-text-6").innerHTML = "Lorem Epsom is a fake text produced with incomprehensible simplicity from the printing industry and using graphic designers, printers and texts, but also newspapers and magazines in columns and rows as necessary."
      document.getElementById("about-body-text-7").innerHTML = "Lorem ipsum dolor"
      document.getElementById("about-body-text-8").innerHTML = "Lorem Epsom is a fake text produced with printing industry and using graphic designers, printers and texts, but also newspapers and magazines."
      document.getElementById("about-body-text-9").innerHTML = "Lorem ipsum dolor"
      document.getElementById("about-body-text-10").innerHTML = "Lorem Epsom is a fake text produced with printing industry and using graphic designers, printers and texts, but also newspapers and magazines."
      document.getElementById("about-body-text-11").innerHTML = "Lorem ipsum dolor"
      document.getElementById("about-body-text-12").innerHTML = "Lorem Epsom is a fake text produced with printing industry and using graphic designers, printers and texts, but also newspapers and magazines."
      document.getElementById("about-body-text-13").innerHTML = "Lorem ipsum dolor"
      document.getElementById("about-body-text-14").innerHTML = "Lorem Epsom is a fake text produced with printing industry and using graphic designers, printers and texts, but also newspapers and magazines."
      document.getElementById("services-header-text-1").innerHTML = "services"
      document.getElementById("services-header-text-2").innerHTML = "our services"
      document.getElementById("services-body-text-1").innerHTML = "Lorem Ipsum is a fictional text"
      document.getElementById("services-body-text-2").innerHTML = "Lorem Epsom is a fake text produced with incomprehensible simplicity from the printing industry and using graphic designers, printers and texts, but also newspapers."
      document.getElementById("services-body-text-3").innerHTML = "Lorem Ipsum is a fictional text"
      document.getElementById("services-body-text-4").innerHTML = "Lorem Epsom is a fake text produced with incomprehensible simplicity from the printing industry and using graphic designers, printers and texts, but also newspapers."
      document.getElementById("services-body-text-5").innerHTML = "Lorem Ipsum is a fictional text"
      document.getElementById("services-body-text-6").innerHTML = "Lorem Epsom is a fake text produced with incomprehensible simplicity from the printing industry and using graphic designers, printers and texts, but also newspapers."
      document.getElementById("services-body-text-7").innerHTML = "Lorem Ipsum is a fictional text"
      document.getElementById("services-body-text-8").innerHTML = "Lorem Epsom is a fake text produced with incomprehensible simplicity from the printing industry and using graphic designers, printers and texts, but also newspapers."
      document.getElementById("services-body-text-9").innerHTML = "Lorem Ipsum is a fictional text"
      document.getElementById("services-body-text-10").innerHTML = "Lorem Epsom is a fake text produced with incomprehensible simplicity from the printing industry and using graphic designers, printers and texts, but also newspapers."
      document.getElementById("services-body-text-11").innerHTML = "Lorem Ipsum is a fictional text"
      document.getElementById("services-body-text-12").innerHTML = "Lorem Epsom is a fake text produced with incomprehensible simplicity from the printing industry and using graphic designers, printers and texts, but also newspapers."
      document.getElementById("portfolio-header-text-1").innerHTML = "Protofilo"
      document.getElementById("portfolio-header-text-2").innerHTML = "our Protofilo"
      document.getElementById("portfolio-body-text-1").innerHTML = "Lorem Ipsum mock text with"
      document.getElementById("portfolio-body-text-2").innerHTML = "Lorem Ipsum"
      document.getElementById("portfolio-body-text-3").innerHTML = "Lorem Ipsum mock text with"
      document.getElementById("portfolio-body-text-4").innerHTML = "Lorem Ipsum"
      document.getElementById("portfolio-body-text-5").innerHTML = "Lorem Ipsum mock text with"
      document.getElementById("portfolio-body-text-6").innerHTML = "Lorem Ipsum"
      document.getElementById("portfolio-body-text-7").innerHTML = "Lorem Ipsum mock text with"
      document.getElementById("portfolio-body-text-8").innerHTML = "Lorem Ipsum"
      document.getElementById("portfolio-body-text-9").innerHTML = "Lorem Ipsum mock text with"
      document.getElementById("portfolio-body-text-10").innerHTML = "Lorem Ipsum"
      document.getElementById("portfolio-body-text-11").innerHTML = "Lorem Ipsum mock text with"
      document.getElementById("portfolio-body-text-12").innerHTML = "Lorem Ipsum"
      document.getElementById("team-header-text-1").innerHTML = "Our professional staff"
      document.getElementById("team-header-text-2").innerHTML = "Get to know the professional staff of the Future Green Research Company"
      document.getElementById("team-body-text-1").innerHTML = "Ipsom text"
      document.getElementById("team-body-text-2").innerHTML = "Worm Epsom fake text with the production of incomprehensible simplicity from the printing industry and with stipulation"
      document.getElementById("team-body-text-3").innerHTML = "Ipsom text"
      document.getElementById("team-body-text-4").innerHTML = "Worm Epsom fake text with the production of incomprehensible simplicity from the printing industry and with stipulation"
      document.getElementById("team-body-text-5").innerHTML = "Ipsom text"
      document.getElementById("team-body-text-6").innerHTML = "Worm Epsom fake text with the production of incomprehensible simplicity from the printing industry and with stipulation"
      document.getElementById("team-body-text-7").innerHTML = "Ipsom text"
      document.getElementById("team-body-text-8").innerHTML = "Worm Epsom fake text with the production of incomprehensible simplicity from the printing industry and with stipulation"
      document.getElementById("contact-header-text-1").innerHTML = "contact us"
      document.getElementById("contact-header-text-2").innerHTML = "Contact us for more information"
      document.getElementById("contact-body-text-1").innerHTML = "contact us"
      document.getElementById("contact-body-text-2").innerHTML = "Contact us for more information"
      document.getElementById("contact-body-text-10").innerHTML = "Support... "
      document.getElementById("contact-body-text-3").innerHTML = "our address"
      document.getElementById("contact-body-text-4").innerHTML = "The address of the office of the future research company"
      document.getElementById("contact-body-text-5").innerText = "Mashhad holy shrine of  peace be upon him"
      document.getElementById("contact-body-text-6").innerHTML = "Our email"
      document.getElementById("contact-body-text-7").innerHTML = "Contact us by email"
      document.getElementById("contact-body-text-8").innerHTML = "Green research company in virtual space"
      document.getElementById("contact-body-text-9").innerHTML = "Contact us by email"
      document.documentElement.setAttribute('dir', 'ltr');
      navv.classList.add("offcanvas-start");
      navv.classList.remove("offcanvas-end");
      langSelector.style.backgroundImage="url(source/gallery/united-states-of-america-flag-large.png)"
   }
   if (document.documentElement.getAttribute('lang') == 'fa') {
      document.getElementById("landing-text").innerHTML = "صفحه نخست"
      document.getElementById("about-text").innerHTML = "درباره ما";
      document.getElementById("services-text").innerHTML = "خدمات";
      document.getElementById("protofilo-text").innerHTML = "نمونه کار ها";
      document.getElementById("team-text").innerHTML = "تیم ما";
      document.getElementById("contact-text").innerHTML = "تماس با ما";
      document.getElementById("landing-text-1").innerHTML = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است     "
      document.getElementById("landing-text-2").innerHTML = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ     "
      document.getElementById("landing-text-3").innerHTML = "لورم ایپسوم متن"
      document.getElementById("landing-text-4").innerHTML = "لورم ایپسوم متن"
      document.getElementById("landing-text-5").innerHTML = "لورم ایپسوم متن"
      document.getElementById("about-header-text-1").innerHTML = "درباره ما بیشتر بدانید"
      document.getElementById("about-header-text-2").innerHTML = "درباره ما بیشتر بدانید"
      document.getElementById("about-body-text-1").innerHTML = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم ازصنعت چاپ"
      document.getElementById("about-body-text-2").innerHTML = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است"
      document.getElementById("about-body-text-3").innerHTML = "لورم ایپسوم متن"
      document.getElementById("about-body-text-4").innerHTML = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ"
      document.getElementById("about-body-text-5").innerHTML = "لست چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است"
      document.getElementById("about-body-text-6").innerHTML = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است"
      document.getElementById("about-body-text-7").innerHTML = "لورم ایپسوم متن"
      document.getElementById("about-body-text-8").innerHTML = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است"
      document.getElementById("about-body-text-9").innerHTML = "لورم ایپسوم متن"
      document.getElementById("about-body-text-10").innerHTML = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است"
      document.getElementById("about-body-text-11").innerHTML = "لورم ایپسوم متن"
      document.getElementById("about-body-text-12").innerHTML = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است"
      document.getElementById("about-body-text-13").innerHTML = "لورم ایپسوم متن"
      document.getElementById("about-body-text-14").innerHTML = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است"
      document.getElementById("services-header-text-1").innerHTML = "خدمات"
      document.getElementById("services-header-text-2").innerHTML = "خدمات ما"
      document.getElementById("services-body-text-1").innerHTML = "لورم ایپسوم متن ساختگی"
      document.getElementById("services-body-text-2").innerHTML = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است"
      document.getElementById("services-body-text-3").innerHTML = "لورم ایپسوم متن ساختگی"
      document.getElementById("services-body-text-4").innerHTML = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است"
      document.getElementById("services-body-text-5").innerHTML = "لورم ایپسوم متن ساختگی"
      document.getElementById("services-body-text-6").innerHTML = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است"
      document.getElementById("services-body-text-7").innerHTML = "لورم ایپسوم متن ساختگی"
      document.getElementById("services-body-text-8").innerHTML = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است"
      document.getElementById("services-body-text-9").innerHTML = "لورم ایپسوم متن ساختگی"
      document.getElementById("services-body-text-10").innerHTML = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است"
      document.getElementById("services-body-text-11").innerHTML = "لورم ایپسوم متن ساختگی"
      document.getElementById("services-body-text-12").innerHTML = "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است"
      document.getElementById("portfolio-header-text-1").innerHTML = "محصولات ما"
      document.getElementById("portfolio-header-text-2").innerHTML = "با نمونه محصولات شرکت پژوهش سبز آینده اشنا شوید"
      document.getElementById("portfolio-body-text-1").innerHTML = "لورم ایپسوم متن ساختگی با"
      document.getElementById("portfolio-body-text-2").innerHTML = "لورم ایپسوم متن"
      document.getElementById("portfolio-body-text-3").innerHTML = "لورم ایپسوم متن ساختگی با"
      document.getElementById("portfolio-body-text-4").innerHTML = "لورم ایپسوم متن"
      document.getElementById("portfolio-body-text-5").innerHTML = "لورم ایپسوم متن ساختگی با"
      document.getElementById("portfolio-body-text-6").innerHTML = "لورم ایپسوم متن"
      document.getElementById("portfolio-body-text-7").innerHTML = "لورم ایپسوم متن ساختگی با"
      document.getElementById("portfolio-body-text-8").innerHTML = "لورم ایپسوم متن"
      document.getElementById("portfolio-body-text-9").innerHTML = "لورم ایپسوم متن ساختگی با"
      document.getElementById("portfolio-body-text-10").innerHTML = "لورم ایپسوم متن"
      document.getElementById("portfolio-body-text-11").innerHTML = "لورم ایپسوم متن ساختگی با"
      document.getElementById("portfolio-body-text-12").innerHTML = "لورم ایپسوم متن"

      document.getElementById("team-header-text-1").innerHTML = "کادر حرفه ای ما"
      document.getElementById("team-header-text-2").innerHTML = "با کادر حرفه ای شرکت پژوهش سبز آینده اشنا شوید"
      document.getElementById("team-body-text-1").innerHTML = "ایپسوم متن"
      document.getElementById("team-body-text-2").innerHTML = "ورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفا"
      document.getElementById("team-body-text-3").innerHTML = "ایپسوم متن"
      document.getElementById("team-body-text-4").innerHTML = "ورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفا"
      document.getElementById("team-body-text-5").innerHTML = "ایپسوم متن"
      document.getElementById("team-body-text-6").innerHTML = "ورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفا"
      document.getElementById("team-body-text-7").innerHTML = "ایپسوم متن"
      document.getElementById("team-body-text-8").innerHTML = "ورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفا"
      document.getElementById("contact-header-text-1").innerHTML = "تماس با ما     "
      document.getElementById("contact-header-text-2").innerHTML = "برای اطالاعات بیشتر با ما در تماس باشید"
      document.getElementById("contact-body-text-1").innerHTML = "تماس با ما"
      document.getElementById("contact-body-text-2").innerHTML = "برای ارتباط بیشتر با ما در تماس باشید"
      document.getElementById("contact-body-text-10").innerHTML = "پشتیبانی "
      document.getElementById("contact-body-text-3").innerHTML = "آدرس ما"
      document.getElementById("contact-body-text-4").innerHTML = "آدرس دفتر شرکت پژوهش سبز آینده"
      document.getElementById("contact-body-text-5").innerText = "مشهد، حرم مطهر امام رضا (علیه السلام)."
      document.getElementById("contact-body-text-6").innerHTML = "پست الکترونیکی ما"
      document.getElementById("contact-body-text-7").innerHTML = "با ما از طریق پست الکترونیکی در ارتباط باشید"
      document.getElementById("contact-body-text-8").innerHTML = "شرکت پژوهش سبز در فضا مجازی"
      document.getElementById("contact-body-text-9").innerHTML = "با ما از طریق پست الکترونیکی در ارتباط باشید"
      document.documentElement.setAttribute('dir', 'rtl');
      navv.classList.remove("offcanvas-start");
      navv.classList.add("offcanvas-end");
      langSelector.style.backgroundImage=" url(source/gallery/iran-flag-xs.png)"
   }
})